version: 2
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-latest
  commands:
    - mamba install -c conda-forge/label/rust_dev -c conda-forge -c nodefaults pixi rust
    - pixi run -e docs readthedocs
sphinx:
  configuration: docs/conf.py
formats:
  - pdf
