version: 2
build:
  os: ubuntu-24.04
  tools:
    python: mambaforge-latest
  commands:
    - mamba install -c conda-forge -c nodefaults pixi
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - rustup install
    - pixi run -e docs readthedocs
sphinx:
  configuration: docs/conf.py
formats:
  - pdf
