[package]
edition = "2021"
name = "dataframely"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "dataframely"

[dependencies]
itertools = "*"
num-format = "*"
polars = { version = ">=0.50", default-features = false, features = [
  "dtype-full",
] }
polars-arrow = ">=0.50"
polars-core = ">=0.50"
pyo3 = { version = ">=0.25", features = ["abi3-py310", "extension-module"] }
pyo3-polars = { version = ">=0.23.1", features = ["derive", "dtype-full"] }
rand = { version = "0.9", features = ["std_rng"] }
rayon = "*"
regex = "*"
regex-syntax = "0.8"
serde = "*"
thiserror = "2.0"

# Keep the Polars crates on the same revision as pyo3-polars for compatible Rust types.
[patch.crates-io]
polars = { git = "https://github.com/borchero/polars", rev = "639ac9605b5d725e656fbba574402930dd47df50" }
polars-arrow = { git = "https://github.com/borchero/polars", rev = "639ac9605b5d725e656fbba574402930dd47df50" }
polars-core = { git = "https://github.com/borchero/polars", rev = "639ac9605b5d725e656fbba574402930dd47df50" }
# FIXME: Switch back to a pyo3-polars release once https://github.com/pola-rs/polars/pull/29385 is released.
pyo3-polars = { git = "https://github.com/borchero/polars", rev = "639ac9605b5d725e656fbba574402930dd47df50" }

[dev-dependencies]
rstest = "*"

[profile.release]
codegen-units = 1
lto = true
